# Form implementation generated from reading ui file '8_window.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(402, 142)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout.addWidget(self.checkBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(Form)
        self.label.setStyleSheet("QLabel{\n"
"color:\'red\'\n"
"}\n"
"\n"
"QCheckBox{\n"
"color:\'green\'\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(Form)
        self.checkBox.toggled.connect(self.item_selected)
        self.checkBox_2.toggled.connect(self.item_selected)
        self.checkBox_3.toggled.connect(self.item_selected)

        QtCore.QMetaObject.connectSlotsByName(Form)

    def item_selected(self):
        value = ""
        if self.checkBox.isChecked():
            value = self.checkBox.text()
        if self.checkBox_2.isChecked():
            value = self.checkBox_2.text()
        if self.checkBox_3.isChecked():
            value = self.checkBox_3.text()
        self.label.setText("You have selected:" + value)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBox.setText(_translate("Form", "Java"))
        self.checkBox_2.setText(_translate("Form", "C#"))
        self.checkBox_3.setText(_translate("Form", "C++"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
